apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "havadurumu.name" . }}
  labels:
    {{- include "havadurumu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "havadurumu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "havadurumu.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "havadurumu.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "havadurumu.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "havadurumu.name" . }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 8
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 25
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
